from autogen_agentchat.agents import AssistantAgent
from autogen_ext.models.openai import OpenAIChatCompletionClient
from autogen_agentchat.messages import TextMessage
from autogen_core import CancellationToken
from dotenv import load_dotenv
import asyncio
import os
import requests
import json
load_dotenv()

#using TextMessage 

async def main(question):
    openai_api_key = os.getenv("OPENAI_API_KEY")
    
    model_client = OpenAIChatCompletionClient(model="gpt-4o-mini", api_key=openai_api_key)
    
    assistant = AssistantAgent(name="Helpful_Assistant_Agent",
                                 model_client=model_client,
                                 system_message="You are a helpful assistant that provides accurate and concise answers to user queries.")  
    
    text_message = TextMessage(content=question, source="user")
    result = await assistant.on_messages(
        messages=[text_message],
        cancellation_token=CancellationToken()
    )
    print(result)
    
asyncio.run(main('Tell me about Autogen?'))

#output:
# Response(
    # chat_message=TextMessage(id='b8c4a82c-f8ab-4bbd-839a-a0f2deef1b68', 
    # source='Helpful_Assistant_Agent', 
    # models_usage=RequestUsage( prompt_tokens=33, completion_tokens=224), metadata={}, created_at=datetime.datetime(2026, 4, 9, 4, 30, 16, 681147, tzinfo=datetime.timezone.utc), 
    # content='"Autogen" can refer to several different concepts or technologies, depending on the context. Here are a few possibilities:\n\n1. **Autogenerated Content**: In software development, "autogen" often relates to the automatic generation of code or content. This might include scripts, documentation, or configuration files created by tools that analyze existing codebases or templates.\n\n2. **Autogen in AI**: In the context of artificial intelligence and machine learning, it can refer to systems that automatically generate data, text, or even synthetic media based on trained models. This includes natural language processing tools that produce human-like text outputs.\n\n3. **Software Tools**: There are various software tools specifically named "Autogen" that are designed for different purposes, such as automated documentation generation or configuration management in programming environments.\n\n4. **Autogen for Aviation**: In another context, especially related to aviation simulations, "Autogen" could refer to the automatic generation of scenery or objects in flight simulation software.\n\nIf you can provide a bit more context about the specific area you\'re interested in, I can offer a more detailed response!', type='TextMessage'), 
    # inner_messages=[])